CREATE ROLE app WITH
LOGIN
NOSUPERUSER
INHERIT
NOCREATEDB
NOCREATEROLE
NOREPLICATION
PASSWORD 'mdm_ALULA3155';

//alter user mdm with password 'mdm_ALULA3155';


GRANT as_admin TO app;
CREATE SCHEMA app AUTHORIZATION as_admin;
GRANT ALL ON SCHEMA app TO as_admin;
GRANT USAGE ON SCHEMA app TO app;
ALTER ROLE app SET search_path TO app;